// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhvygfyeemqiuwhlehti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodnlnZnllZW1xaXV3aGxlaHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTY5MjEsImV4cCI6MjA2MzIzMjkyMX0.IPdWpE-w2JnNH-bTr4yyT6hYdx_Vv7kGOwBMJpsZne4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);