// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evtzcardsedazhxugntw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dHpjYXJkc2VkYXpoeHVnbnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjQwOTEsImV4cCI6MjA2MTg0MDA5MX0.Vtr22q--MqYM1JzyQtd80hUR-Vi92Hfq7xmi3BUYAeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);