
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahhifmvhwwsguxbxqhfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoaGlmbXZod3dzZ3V4YnhxaGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODYzMDksImV4cCI6MjA2MzM2MjMwOX0.pcIBds_rhACg-BVBE_rOX1zqgKQK9kWHkD7Cb1OCm50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
